import {
  PayCircleOutlined,
  ShoppingCartOutlined,
  MessageOutlined,
  TeamOutlined,
  UserOutlined,
  CalendarOutlined,
  DashboardOutlined,
  ApiOutlined,
  SmileOutlined,
  CameraOutlined,
  EditOutlined,
  CodeOutlined,
  LineOutlined,
  BarChartOutlined,
  AreaChartOutlined,
  HomeOutlined,
  VideoCameraOutlined,
  CarOutlined,
  UsergroupAddOutlined,
  GiftOutlined,
} from '@ant-design/icons'

export default {
  'home': <HomeOutlined />,
  'emcee': <UserOutlined />,
  'dresser': <SmileOutlined />,
  'video': <VideoCameraOutlined />,
  'car': <CarOutlined />,
  'wedding-album': <UsergroupAddOutlined />,
  'wedding-gift': <GiftOutlined />,
  'schedule': <CalendarOutlined />,
  'pay-circle-o': <PayCircleOutlined />,
  'shopping-cart': <ShoppingCartOutlined />,
  'camera-o': <CameraOutlined />,
  'line-chart': <LineOutlined />,
  'code-o': <CodeOutlined />,
  'area-chart': <AreaChartOutlined />,
  'bar-chart': <BarChartOutlined />,
  message: <MessageOutlined />,
  team: <TeamOutlined />,
  dashboard: <DashboardOutlined />,
  user: <UserOutlined />,
  api: <ApiOutlined />,
  edit: <EditOutlined />,
}
